#!/usr/bin/python2

import re
import sys
import linecache


def check(znaki):
	pattern1 = r'\D'
	dopasowanie1 = re.search(pattern1,znaki)
        if dopasowanie1:
            return 0
        else:
            return 1

def count():
    linecount = len(open(sys.argv[1], 'rU').readlines())
    i=1
    while i<=linecount:
        stan=0
        line=linecache.getline(sys.argv[1],i)
        line=line.replace(" ","")
        nline=line[0:2]
        nline=str(nline)
        if 0==check(nline):
            print "fail"
            i=i+1
        else:
            a=nline[0]
            b=nline[1]
            a=int(a)
            b=int(b)
            if a==b-1:
                stan=stan+1
                i=i+1
    print stan

count()
#for line in sys.stdin:
#	count()

